/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import connection.PythonConnector;
import connection.PythonRunner;
import faceID.FaceChecker;

public class App {

    SkillLoader skillLoader;
    public static String appPath = "app/src/main/java/";
    public static String resourcesPath = "app/src/main/resources/";
    private static final boolean CHECK_FACE = true;
    /**
     * App starting point
     */
    public void init(){
        // 1) Load grammar from file
        skillLoader = new SkillLoader();
        skillLoader.loadCFGandCNF();

        // 2) Start Face checker
        if(CHECK_FACE){
            FaceChecker faceChecker = new FaceChecker();

            if(faceChecker.checkFace()){
                startAppAfterFaceCheck();
            }
        }else{
            startAppAfterFaceCheck();
        }
    }

    private void startAppAfterFaceCheck(){
        // 3) Start Java-Python bridge
        new PythonRunner().runPythonScript("app/src/main/python/main.py");

        PythonConnector pythonConn = new PythonConnector();
        pythonConn.open();

        // 4) Start GUI
        new Frame(this);

        //TEst
        try {
            System.out.println("Response: "+pythonConn.askCosineSimilarity());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public SkillLoader getSkillLoader() {
        return skillLoader;
    }

    public static void main(String[] args) {
        if (App.class.getResource("/GradleResourceChecker") == null){
            System.err.println("Error: Please run the program using Gradle ( > Gradle run )");
            return;
        }
        new App().init();
    }
}
