/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

public class App {

    SkillLoader skillLoader;
    /**
     * App starting point
     */
    public void init(){
        // 1) Load grammar from file
        skillLoader = new SkillLoader();
        skillLoader.loadCFGandCNF();
        // 2) Initialize the skill data for the skill editor

        // 3) Start GUI
        new Frame(this);

    }

    public SkillLoader getSkillLoader() {
        return skillLoader;
    }

    public static void main(String[] args) {
        if (App.class.getResource("/GradleResourceChecker") == null){
            System.err.println("Error: Please run the program using Gradle ( > Gradle run )");
            return;
        }
        new App().init();
    }
}
